[package]
name = "rme"
version = "0.1.0"
authors = ["Evgeniy Nochevnov <xpath@e1.ru>"]

[dependencies]
rocket = "0.4.0"
dotenv = "0.13.0"
diesel = { version = "1.3.0", features = ["postgres"] }
chrono = "0.4.6"
